print("\n Elaborar un algoritmo que convierta una medida de masa en toneladas a: kilogramos, quintales, gramos, libras. \n ")
TONELADAS = float(input("INGRESA TONELADAS A CONVERTIR:"))
K = TONELADAS * 1000 
Q = TONELADAS * 10 #TENIENDO EN CUENTA QUE 1 QUINTAL EQUIVALE A 100 KG
GR = TONELADAS * (1000*1000) # TENIENDO EN CUENTA QUE 1 TONELADA EQUIVALE A 1000 KG 1 KG EQUIVALE A 100 GR
L = TONELADAS * (1000/0.453592) # TENIENDO EN CUIENTA QUE UNA LIBRA EQUIVALE A 0.453591 KG

print(f"\n TONELADAS A CARGAR: {TONELADAS}\n EQUIVALENCIAS EN: \n  \n KILOGRAMOS: {K} K \n QUINTALES: {Q} Q \n GRAMOS: {GR} \n GR LIBRAS {L} L\n\n GRACIAS POR USAR NUESTRA APP")
print(f"")

