print("\n Elaborar un algoritmo que convierta una medida de longitud en kilometros \n a metros, centímetros, milímetros, pulgadas, yardas, millas y pies \n ")
KILOMETROS = float(input("INGRESA KILOMETROS RECORRIDOS:"))
M = KILOMETROS * 1000 
CM = KILOMETROS * 100000
MM = KILOMETROS * 1000000
P = KILOMETROS * (100000/2.54) # 1 PULGADA EQUIVALE A 2,54 CENTIMETROS
PI = KILOMETROS * ((100000/2.54)/12) # 1 PIE EQUIVALE A 12 PULGADAS
Y = KILOMETROS * (((100000/2.54)/12)/3) # 1 YARDA EQUIVALE A 3 PIES
MI = KILOMETROS * ((((100000/2.54)/12)/3)/1760) # 1 MILLA EQUIVALE A 1760 YARDAS

print(f"\n KILOMETROS RECORRIDOS: {KILOMETROS}\n EQUIVALENCIAS EN: \n  \n METROS: {M} M \n CEMTIMETROS: {CM} CM \n MILIMETROS: {MM} MM \n PULGADAS: {P} P \n PIES: {PI} PI \n YARDAS: {Y} Y \n MILLAS: {MI} MI  \n \n GRACIAS POR HACER EL RECORRIDO CON NUESTRA APP")
